-- Tabla USUARIO
CREATE TABLE Usuario (
    id_usuario    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    nombre        VARCHAR2(50)    NOT NULL,
    correo        VARCHAR2(100)   NOT NULL,
    contrasena    VARCHAR2(20)    NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (id_usuario)
);

-- Tabla CATEGORIA (Corregida)
CREATE TABLE Categoria (
    id_categoria   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    nombre        VARCHAR2(50)    NOT NULL,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (id_categoria)
);

-- Tabla PRODUCTO (Corregida)
CREATE TABLE Producto (
    id_producto   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    id_categoria  NUMBER NOT NULL,
    nombre        VARCHAR2(50)    NOT NULL,
    descripcion   VARCHAR2(100),  -- La columna puede ser nula por defecto, no se necesita "NULL,"
    precio        NUMBER(15,4)     NOT NULL,
    stock         NUMBER(5)     NOT NULL,
    imagen        VARCHAR2(500),  -- La columna puede ser nula por defecto, no se necesita "NULL,"
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (id_producto),
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (id_categoria) REFERENCES Categoria (id_categoria)
);

-- Tabla PAGO
CREATE TABLE Pago (
    id_pago             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    monto               NUMBER(15,4)     NOT NULL,
    CONSTRAINT PK_PAGO PRIMARY KEY (id_pago)
);

-- Tabla ESTADO_PEDIDO
CREATE TABLE Estado_Pedido (
    id_estadoPedido     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    descripcion         VARCHAR2(50)    NOT NULL,
    CONSTRAINT PK_ESTADO_PAGO PRIMARY KEY (id_estadoPedido)
);

-- Tabla PEDIDO
CREATE TABLE Pedido (
    id_pedido     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    id_usuario    NUMBER          NOT NULL,
    id_pago       NUMBER          NOT NULL,
    id_estadoPedido NUMBER        NOT NULL,
    fecha         DATE            NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (id_pedido),
    CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (id_usuario) REFERENCES Usuario (id_usuario),
    CONSTRAINT FK_PEDIDO_PAGO FOREIGN KEY (id_pago) REFERENCES Pago (id_pago),
    CONSTRAINT FK_PEDIDO_ESTADO_PEDIDO FOREIGN KEY (id_estadoPedido) REFERENCES Estado_Pedido (id_estadoPedido)
);

-- Tabla DETALLE_PEDIDO
CREATE TABLE Detalle_Pedido (
    id_detallePedido    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    id_pedido           NUMBER          NOT NULL, -- Corregido a NUMBER para coincidir con id_pedido en Pedido
    id_producto         NUMBER          NOT NULL, -- Corregido a NUMBER para coincidir con id_producto en Producto
    cantidad            NUMBER(15)     NOT NULL,
    precio              NUMBER(15,4)     NOT NULL,
    CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (id_detallePedido),
    CONSTRAINT FK_DETALLE_PEDIDO_PEDIDO FOREIGN KEY (id_pedido) REFERENCES Pedido (id_pedido),
    CONSTRAINT FK_DETALLE_PEDIDO_PRODUCTO FOREIGN KEY (id_producto) REFERENCES Producto (id_producto)
);

truncate table detalle_pedido;
truncate table pedido;
truncate table pago;